name: CI Workflow Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create webapp
      run: dotnet new webapp -n github4women

    - name: Install dependencies
      run: dotnet restore **/*.csproj

    - name: Build the application
      run: dotnet build **/*.csproj --no-restore

    - name: Custom script
      run: |
        echo "Running custom script"
        # Add your custom commands here
        dotnet run --project **/*.csproj
